spring:
  profiles:
    active: master
  application:
    name: eureka-service-consumer1

  security:
    user:
      name: root
      password: root


#开启springcloud的重试功能
#  cloud:
#    loadbalancer:
#      retry:
#        enabled: true
